### ISSUE TITLE
Popup Displays Underneath Open Sheet Instead of On Top

### ISSUE THREAD

**Issue by elriando** [Mijick/PopupView#87]
Hello, I've been using your excellent library, and it works very well. However, I've encountered an issue: when I am in a sheet and try to display a Popup, it opens underneath the currently open sheet, whereas I would like it to appear on top. I hope you can find a solution to this problem.

**Comment by FulcrumOne** [comment]
hey @elriando,

We are aware of this problem, but unfortunately I doubt I will be able to provide a solution without refactoring the whole library (which I plan to do, but once I have finished gathering all the feedback on features that might be good to include in the 'final' product). 
Here you can find an explanation of why this is impossible with the current architecture - https://github.com/Mijick/PopupView/issues/77#issuecomment-1998549280.

As a workaround, I would suggest replacing the sheet with our BottomPopup, which provides roughly the same functionality as Apple's native sheet.

Sorry again, but when I was designing this library, I assumed it would completely replace the Apple's sheets, alerts, etc. and that's why it works like this 😉 

Have a great evening and feel free to ask if you have any further questions!
